# Generated by Django 5.0.2 on 2024-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=25),
        ),
    ]
